name: Streamlit App Tests

on:
  pull_request:
    branches:
       -main

jobs:
  test: 
    runs-on: ubuntu-latest


    strategy:
      matrix:
        python-version: [python3.8.10]


    steps:
      - uses: actions/checkput@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyton-version }}    


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test App Code
        run: python main_test.py      