name: Convert PO to Markdown

on:
  push:
    branches:
      - main 

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install mdpo
        run: |
          pip install mdpo

      - name: Convert PO to MD
        run: |
          mdpo convert po_files/test1.po md_files/test.md
