name: PO to Markdown Conversion

on:
  push:
    branches:
      - main 

jobs:
  convert:
    name: Convert PO to Markdown
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gettext
      run: sudo apt-get update && sudo apt-get install -y gettext

    - name: Convert PO to Markdown
      run: |
        # Assuming your PO files are in a directory called 'po'
        # and you want to output the Markdown files to a directory called 'markdown'
        mkdir -p markdown
        for po_file in po/*.po; do
          base_file=$(basename "$po_file" .po)
          msgfmt -o "markdown/${base_file}.md" "$po_file"
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add markdown
        git commit -m "Converted PO files to Markdown"
        git push
