name: Install calbmi-lungsang and print success

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install calbmi-lungsang

      - name: Check installation
        run: |
          python -c "import calbmi_lungsang"
          echo "success!"

